title: Programming Chi - Tomasz Fijałkowski's blog
description: Programming Chi is a blog about pitiful ideas, bugs and failures I notice every day. Fortunately, besides failures there are also a lot of successes and beautiful solution which I hope I will also write about.
author: Tomasz Fijałkowski
menu: false
baseurl: ""
twitter_username: tomaszfialkows
github_username:  tfij
env: prod
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      image: /assets/img/chi.svg
paginate: 10
paginate_path: "/blog/page/:num/"
