title: Programming Chi
description: Tomek FijaŁkowski's programming blog
menu: false
baseurl: ""
twitter_username: tomaszfialkows
github_username:  tfij
env: prod
gems:
  - jekyll-feed
  - jekyll-sitemap
