title: Programming Chi
description: Tomasz Fijałkowski's programming blog
author: Tomasz Fijałkowski
menu: false
baseurl: ""
twitter_username: tomaszfialkows
github_username:  tfij
env: prod
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      image: /assets/img/chi.svg
